import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { api } from './api'
import './featured.css'
import type { Article, Category, Country, FeaturedBrief, Source, Translation } from './types'

type Tab = 'home' | 'featured' | 'saved' | 'settings'
type Locale = 'en' | 'vi'
type Filters = { category: string; source: string; country: string; query: string }
const flags: Record<string, string> = { GLOBAL: '◉', HK: '🇭🇰', GB: '🇬🇧', US: '🇺🇸', CN: '🇨🇳', SG: '🇸🇬', DE: '🇩🇪', QA: '🇶🇦', EU: '🇪🇺' }
const categories: Record<string, Record<Locale, string>> = { technology: { en: 'Technology', vi: 'Công nghệ' }, world: { en: 'World', vi: 'Thế giới' }, business: { en: 'Business', vi: 'Kinh doanh' }, society: { en: 'Society', vi: 'Xã hội' }, culture: { en: 'Culture', vi: 'Văn hóa' }, sports: { en: 'Sports', vi: 'Thể thao' }, education: { en: 'Education', vi: 'Giáo dục' }, health: { en: 'Health', vi: 'Sức khỏe' }, science: { en: 'Science', vi: 'Khoa học' } }
const countries: Record<string, Record<Locale, string>> = { GLOBAL: { en: 'Global', vi: 'Toàn cầu' }, HK: { en: 'Hong Kong', vi: 'Hồng Kông' }, GB: { en: 'United Kingdom', vi: 'Vương quốc Anh' }, US: { en: 'United States', vi: 'Hoa Kỳ' }, CN: { en: 'China', vi: 'Trung Quốc' }, SG: { en: 'Singapore', vi: 'Singapore' }, DE: { en: 'Germany', vi: 'Đức' }, QA: { en: 'Qatar', vi: 'Qatar' }, EU: { en: 'European Union', vi: 'Liên minh châu Âu' } }
const text = {
  en: { masthead: 'SIGNAL BRIEF', news: 'Briefs', saved: 'Saved', filter: '☷ Filter', newest: 'Latest', all: 'All', featured: 'FEATURED', featuredNews: 'Featured', featuredUpdated: 'Updated', featuredUnavailable: 'No featured briefing is available yet.', yourArticles: 'Your articles', latest: 'Latest', articles: 'briefs', loading: 'Loading briefs…', empty: 'No matching briefs found.', filters: 'Filters', search: 'Search', allCategories: 'All categories', allSources: 'All sources', allCountries: 'All countries', viewResults: 'View results', home: 'Home', settings: 'Settings', interface: 'INTERFACE', theme: 'Theme follows Telegram.', back: '← Back', readOriginal: 'Read original article', translating: 'Translating to Vietnamese…', translationError: 'Could not translate this article. Showing the original text.', retry: 'Try again', language: 'Language', summary: 'SUMMARY', articleContent: 'ARTICLE', source: 'Source' },
  vi: { masthead: 'SIGNAL BRIEF', news: 'Tóm tắt', saved: 'Đã lưu', filter: '☷ Lọc', newest: 'Mới nhất', all: 'Tất cả', featured: 'NỔI BẬT', featuredNews: 'Nổi bật', featuredUpdated: 'Cập nhật', featuredUnavailable: 'Chưa có bản tin nổi bật.', yourArticles: 'Bài tóm tắt đã lưu', latest: 'Mới nhất', articles: 'bản tóm tắt', loading: 'Đang tải bản tóm tắt…', empty: 'Không tìm thấy bản tóm tắt phù hợp.', filters: 'Bộ lọc', search: 'Tìm kiếm', allCategories: 'Tất cả thể loại', allSources: 'Tất cả nguồn', allCountries: 'Tất cả quốc gia', viewResults: 'Xem kết quả', home: 'Trang chủ', settings: 'Cài đặt', interface: 'INTERFACE', theme: 'Theme tự động theo Telegram.', back: '← Quay lại', readOriginal: 'Đọc bài gốc', translating: 'Translating to Vietnamese…', translationError: 'Không thể dịch bài này. Đang hiển thị nội dung gốc.', retry: 'Thử lại', language: 'Ngôn ngữ', summary: 'TÓM TẮT', articleContent: 'NỘI DUNG BÀI VIẾT', source: 'Nguồn' },
} as const
const category = (slug: string, locale: Locale) => categories[slug]?.[locale] ?? slug
const country = (code: string, fallback: string, locale: Locale) => countries[code]?.[locale] ?? fallback
const ago = (value: string, locale: Locale) => { const minutes = Math.floor((Date.now() - new Date(value).getTime()) / 60000); if (minutes < 60) return locale === 'vi' ? `${Math.max(1, minutes)} phút` : `${Math.max(1, minutes)}m ago`; if (minutes < 1440) return locale === 'vi' ? `${Math.floor(minutes / 60)} giờ` : `${Math.floor(minutes / 60)}h ago`; return new Date(value).toLocaleDateString(locale === 'vi' ? 'vi-VN' : 'en-US', { day: '2-digit', month: 'short' }) }
const publishedOn = (value: string, locale: Locale) => new Intl.DateTimeFormat(locale === 'vi' ? 'vi-VN' : 'en-US', { day: '2-digit', month: 'long', year: 'numeric' }).format(new Date(value))
const open = (url: string) => window.Telegram?.WebApp ? window.Telegram.WebApp.openLink(url) : window.open(url, '_blank', 'noopener,noreferrer')
const articlePath = (article: Article) => `/news/${article.id}-${article.title.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 90) || 'article'}`
const articleIDFromPath = () => { const match = window.location.pathname.match(/^\/news\/(\d+)(?:-|$)/); return match ? Number(match[1]) : null }
const textOnly = (value: string) => { if (!value.includes('<')) return value; return new DOMParser().parseFromString(value, 'text/html').body.textContent?.trim() || '' }
const safeLink = (value: string | null) => { try { const url = new URL(value || '', window.location.origin); return ['http:', 'https:'].includes(url.protocol) ? url.href : '' } catch { return '' } }
function FormattedDescription({ value }: { value: string }) { const doc = new DOMParser().parseFromString(value, 'text/html'); const render = (node: Node, key: string): ReactNode => { if (node.nodeType === Node.TEXT_NODE) return node.textContent; if (node.nodeType !== Node.ELEMENT_NODE) return null; const element = node as HTMLElement; const children = Array.from(element.childNodes).map((child, index) => render(child, `${key}-${index}`)); if (element.tagName === 'BR') return <br key={key}/>; if (element.tagName === 'HR') return <hr className="detail-rule" key={key}/>; if (element.tagName === 'P') return <p className="detail-paragraph" key={key}>{children}</p>; if (element.tagName === 'A') { const href = safeLink(element.getAttribute('href')); return href ? <a className="detail-link" href={href} onClick={event => { event.preventDefault(); open(href) }} key={key}>{children}</a> : <span key={key}>{children}</span> }; return <span key={key}>{children}</span> }; return <div className="detail-description">{Array.from(doc.body.childNodes).map((node, index) => render(node, String(index)))}</div> }

type DropdownOption = { value: string; label: string }
function Dropdown({ value, options, onChange, label, className = '' }: { value: string; options: DropdownOption[]; onChange: (value: string) => void; label: string; className?: string }) {
  const [open, setOpen] = useState(false); const root = useRef<HTMLDivElement>(null); const selected = options.find(option => option.value === value) ?? options[0]
  useEffect(() => { if (!open) return; const close = (event: MouseEvent) => { if (!root.current?.contains(event.target as Node)) setOpen(false) }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close) }, [open])
  const choose = (next: string) => { onChange(next); setOpen(false) }
  const move = (direction: number) => { const index = Math.max(0, options.findIndex(option => option.value === value)); choose(options[(index + direction + options.length) % options.length].value) }
  return <div className={`dropdown ${open ? 'open' : ''} ${className}`} ref={root} onKeyDown={event => { if (event.key === 'Escape') setOpen(false) }}><button type="button" className="dropdown-trigger" aria-label={label} aria-haspopup="listbox" aria-expanded={open} onClick={() => setOpen(current => !current)} onKeyDown={event => { if (event.key === 'ArrowDown') { event.preventDefault(); open ? move(1) : setOpen(true) } if (event.key === 'ArrowUp') { event.preventDefault(); open ? move(-1) : setOpen(true) } }}>{selected?.label}<span className="dropdown-chevron" aria-hidden="true" /></button>{open && <div className="dropdown-menu" role="listbox" aria-label={label}>{options.map(option => <button type="button" role="option" aria-selected={option.value === value} className={option.value === value ? 'selected' : ''} onClick={() => choose(option.value)} key={option.value}>{option.label}</button>)}</div>}</div>
}
function LanguagePicker({ locale, setLocale }: { locale: Locale; setLocale: (locale: Locale) => void }) { return <Dropdown className="language-picker" value={locale} onChange={value => setLocale(value as Locale)} label="Language" options={[{ value: 'en', label: 'English' }, { value: 'vi', label: 'Tiếng Việt' }]} /> }
function Card({ article, hero, locale, toggle, openDetail }: { article: Article; hero?: boolean; locale: Locale; toggle: (article: Article) => void; openDetail: (article: Article) => void }) { const t = text[locale]; return <article className={hero ? 'hero-card' : 'news-card'} onClick={() => openDetail(article)}>{article.image_url ? <img src={article.image_url} alt="" /> : <div className="cover-placeholder">NEWS</div>}<div className="card-copy"><div className="eyebrow">{article.source} · {flags[article.country_code] || '◉'} {country(article.country_code, article.country_name, locale)} · {ago(article.published_at, locale)} · {publishedOn(article.published_at, locale)}</div><h2>{article.title}</h2>{article.summary && <p>{textOnly(article.summary)}</p>}<div className="card-footer"><span className="category-label">{category(article.category, locale)}</span><a className="source-citation" href={article.url} onClick={event => { event.stopPropagation(); event.preventDefault(); open(article.url) }}>{t.source}: {article.source} ↗</a></div></div><button className={`save ${article.is_saved ? 'active' : ''}`} onClick={e => { e.stopPropagation(); toggle(article) }}>{article.is_saved ? '★' : '☆'}</button></article> }

function Detail({ article, locale, back }: { article: Article; locale: Locale; back: () => void }) { const [translation, setTranslation] = useState<Translation | null>(null); const [loading, setLoading] = useState(false); const [failed, setFailed] = useState(false); const t = text[locale]; const translate = () => { if (locale !== 'vi') return; setLoading(true); setFailed(false); api.translateVietnamese(article.id).then(setTranslation).catch(() => setFailed(true)).finally(() => setLoading(false)) }; useEffect(() => { setTranslation(null); setFailed(false); if (locale === 'vi') translate() }, [article.id, locale]); const title = translation?.title || article.title; const summary = translation?.summary || article.summary; const originalDetail = article.description || article.summary; const contentImages = article.content_images?.filter(image => image !== article.image_url) ?? []; return <section className="page detail"><button className="back-button" onClick={back}>{t.back}</button><p className="eyebrow">{article.source} · {publishedOn(article.published_at, locale)} · {ago(article.published_at, locale)}</p>{article.image_url && <img className="detail-image" src={article.image_url} alt="" />}<span className="category-label">{category(article.category, locale)}</span><h1>{title}</h1><a className="detail-citation" href={article.url} onClick={event => { event.preventDefault(); open(article.url) }}>{t.source}: {article.source} ↗</a>{loading && <p className="translation-loading" role="status"><span className="loading-spinner" aria-hidden="true" />{t.translating}</p>}{failed && <p className="state error">{t.translationError} <button className="text-button" onClick={translate}>{t.retry}</button></p>}{summary && <section className="summary-panel"><small>{t.summary}</small><p>{textOnly(summary)}</p></section>}{originalDetail && <section className="article-content"><small>{t.articleContent}</small><FormattedDescription value={originalDetail}/>{contentImages.length > 0 && <div className="article-image-gallery">{contentImages.map((image, index) => <img src={image} alt="" loading="lazy" key={image || index}/>)}</div>}</section>}<button className="primary source-link" onClick={() => open(article.url)}>{t.readOriginal}</button></section> }

function Home({ saved, locale, setLocale, openDetail }: { saved?: boolean; locale: Locale; setLocale: (locale: Locale) => void; openDetail: (article: Article) => void }) {
  const [items, setItems] = useState<Article[]>([]); const [cats, setCats] = useState<Category[]>([]); const [sources, setSources] = useState<Source[]>([]); const [countryList, setCountryList] = useState<Country[]>([]); const [filter, setFilter] = useState<Filters>({ category: '', source: '', country: '', query: '' }); const [loading, setLoading] = useState(true); const [loadingMore, setLoadingMore] = useState(false); const [offset, setOffset] = useState(0); const [hasMore, setHasMore] = useState(true); const [show, setShow] = useState(false); const t = text[locale]
  const params = useMemo(() => new URLSearchParams({ limit: '30', offset: String(offset), lang: locale, ...(filter.category && { category: filter.category }), ...(filter.source && { source: filter.source }), ...(filter.country && { country: filter.country }), ...(filter.query && { q: filter.query }) }), [filter, locale, offset])
  useEffect(() => { if (!saved) Promise.all([api.categories(), api.sources(), api.countries()]).then(([a, b, c]) => { setCats(a); setSources(b); setCountryList(c) }) }, [saved])
  useEffect(() => { setOffset(0); setHasMore(true) }, [filter, locale, saved])
  useEffect(() => { let active = true; if (offset === 0) setLoading(true); else setLoadingMore(true); (saved ? api.saved(locale) : api.articles(params)).then(next => { if (!active) return; setItems(current => offset === 0 ? next : [...current, ...next]); setHasMore(!saved && next.length === 30) }).finally(() => { if (active) { setLoading(false); setLoadingMore(false) } }); return () => { active = false } }, [saved, locale, params, offset])
  useEffect(() => { if (saved) return; const loadMore = () => { if (!loading && !loadingMore && hasMore && window.innerHeight + window.scrollY >= document.documentElement.scrollHeight - 360) setOffset(current => current + 30) }; window.addEventListener('scroll', loadMore, { passive: true }); loadMore(); return () => window.removeEventListener('scroll', loadMore) }, [saved, loading, loadingMore, hasMore])
  const toggle = async (article: Article) => { setItems(current => current.map(item => item.id === article.id ? { ...item, is_saved: !item.is_saved } : item)); try { await api.toggleSaved(article); if (saved && !article.is_saved) setItems(current => current.filter(item => item.id !== article.id)) } catch { setItems(current => current.map(item => item.id === article.id ? { ...item, is_saved: article.is_saved } : item)) } }
  const hero = !saved ? items[0] : undefined; const list = hero ? items.slice(1) : items
  const categoryOptions = [{ value: '', label: t.allCategories }, ...cats.map(item => ({ value: item.slug, label: category(item.slug, locale) }))]; const sourceOptions = [{ value: '', label: t.allSources }, ...sources.map(item => ({ value: String(item.id), label: item.name }))]; const countryOptions = [{ value: '', label: t.allCountries }, ...countryList.map(item => ({ value: item.code, label: country(item.code, item.name, locale) }))]
  return <section className="page editorial"><header className="masthead"><div><p>{t.masthead}</p><h1>{saved ? t.saved : t.news}</h1></div><div className="header-actions"><LanguagePicker locale={locale} setLocale={setLocale}/>{!saved && <button className="filter-button" onClick={() => setShow(true)}>{t.filter}</button>}</div></header>{!saved && <><div className="topic-row"><button className={!filter.category ? 'selected' : ''} onClick={() => setFilter({ ...filter, category: '' })}>{t.newest}</button>{cats.map(item => <button className={filter.category === item.slug ? 'selected' : ''} onClick={() => setFilter({ ...filter, category: item.slug })} key={item.slug}>{category(item.slug, locale)}</button>)}</div><div className="rail">{sources.map(item => <button className={filter.source === String(item.id) ? 'source-pill active' : 'source-pill'} onClick={() => setFilter({ ...filter, source: filter.source === String(item.id) ? '' : String(item.id) })} key={item.id}><b>{item.name}</b><span>{flags[item.country_code] || '◉'} {country(item.country_code, item.country_name, locale)}</span></button>)}</div><div className="country-row"><button className={!filter.country ? 'selected' : ''} onClick={() => setFilter({ ...filter, country: '' })}>{t.all}</button>{countryList.map(item => <button className={filter.country === item.code ? 'selected' : ''} onClick={() => setFilter({ ...filter, country: item.code })} key={item.code}>{flags[item.code] || '◉'} {country(item.code, item.name, locale)}</button>)}</div></>}{loading ? <p className="state">{t.loading}</p> : <>{hero && <><p className="section-kicker">{t.featured}</p><Card hero article={hero} locale={locale} toggle={toggle} openDetail={openDetail}/></>}<div className="feed"><div className="section-head"><h3>{saved ? t.yourArticles : t.latest}</h3><span>{list.length} {t.articles}</span></div>{list.map(item => <Card article={item} locale={locale} toggle={toggle} openDetail={openDetail} key={item.id}/>)}{!items.length && <p className="state">{t.empty}</p>}</div></>}{show && <div className="sheet-backdrop" onClick={() => setShow(false)}><section className="filter-sheet" onClick={e => e.stopPropagation()}><h2>{t.filters}</h2><input value={filter.query} onChange={e => setFilter({ ...filter, query: e.target.value })} placeholder={t.search}/><Dropdown value={filter.category} options={categoryOptions} onChange={category => setFilter({ ...filter, category })} label={t.allCategories}/><Dropdown value={filter.source} options={sourceOptions} onChange={source => setFilter({ ...filter, source })} label={t.allSources}/><Dropdown value={filter.country} options={countryOptions} onChange={country => setFilter({ ...filter, country })} label={t.allCountries}/><button className="primary" onClick={() => setShow(false)}>{t.viewResults}</button></section></div>}</section>
}
function Featured({ locale, setLocale, openDetail }: { locale: Locale; setLocale: (locale: Locale) => void; openDetail: (article: Article) => void }) {
  const [brief, setBrief] = useState<FeaturedBrief | null>(null); const [loading, setLoading] = useState(true); const t = text[locale]
  useEffect(() => { let active = true; setLoading(true); api.featured(locale).then(value => { if (active) setBrief(value) }).catch(() => { if (active) setBrief(null) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [locale])
  const toggle = async (article: Article) => { setBrief(current => current ? { ...current, topics: current.topics.map(topic => ({ ...topic, articles: topic.articles.map(item => item.id === article.id ? { ...item, is_saved: !item.is_saved } : item) })) } : current); try { await api.toggleSaved(article) } catch { setBrief(current => current ? { ...current, topics: current.topics.map(topic => ({ ...topic, articles: topic.articles.map(item => item.id === article.id ? { ...item, is_saved: article.is_saved } : item) })) } : current) } }
  return <section className="page featured-page"><header className="masthead"><div><p>{t.masthead}</p><h1>{t.featuredNews}</h1></div><LanguagePicker locale={locale} setLocale={setLocale}/></header>{loading ? <p className="state">{t.loading}</p> : !brief ? <p className="state">{t.featuredUnavailable}</p> : <><section className="featured-lead"><p className="section-kicker">{t.featuredUpdated} · {publishedOn(brief.generated_at, locale)}</p><h2>{brief.title}</h2><p>{brief.intro}</p></section><div className="featured-topics">{brief.topics.map(topic => <section className="featured-topic" key={topic.id}><span className="category-label">{String(topic.position + 1).padStart(2, '0')}</span><h2>{topic.title}</h2><p>{topic.summary}</p><div className="featured-articles">{topic.articles.map(article => <Card article={article} locale={locale} toggle={toggle} openDetail={openDetail} key={article.id}/>)}</div></section>)}</div></>}</section>
}
function Settings({ locale, setLocale }: { locale: Locale; setLocale: (locale: Locale) => void }) { const t = text[locale]; return <section className="page settings"><h1>{t.settings}</h1><div className="settings-card"><small>{t.language}</small><LanguagePicker locale={locale} setLocale={setLocale}/></div><div className="settings-card"><small>{t.interface}</small><p>{t.theme}</p></div></section> }
export default function App() { const telegramLocale = window.Telegram?.WebApp?.initDataUnsafe?.user?.language_code === 'vi' ? 'vi' : 'en'; const [locale, setLocaleState] = useState<Locale>(() => (localStorage.getItem('locale') as Locale) || telegramLocale); const [tab, setTab] = useState<Tab>('home'); const [article, setArticle] = useState<Article | null>(null); const [articleID, setArticleID] = useState<number | null>(articleIDFromPath); const listingScroll = useRef(0); const setLocale = (next: Locale) => { localStorage.setItem('locale', next); setLocaleState(next) }; const t = text[locale]
  useEffect(() => { const app = window.Telegram?.WebApp; if (app) { app.ready(); app.expand() } }, [])
  useEffect(() => { const onPopState = () => setArticleID(articleIDFromPath()); window.addEventListener('popstate', onPopState); return () => window.removeEventListener('popstate', onPopState) }, [])
  useEffect(() => { if (articleID === null) { setArticle(null); return }; setArticle(current => current?.id === articleID ? current : null); let active = true; api.article(articleID).then(item => { if (active) setArticle(item) }).catch(() => { if (active) setArticle(null) }); return () => { active = false } }, [articleID])
  const openDetail = (next: Article) => { listingScroll.current = window.scrollY; window.history.pushState({}, '', articlePath(next)); setArticle(next); setArticleID(next.id); window.scrollTo(0, 0) }
  const back = () => { if (window.history.state !== null) window.history.back(); else { window.history.replaceState({}, '', '/'); setArticleID(null) }; requestAnimationFrame(() => window.scrollTo(0, listingScroll.current)) }
  const showingDetail = articleID !== null
  return <main><div className="app-shell"><div className={showingDetail ? 'listing-page hidden' : 'listing-page'} aria-hidden={showingDetail}>{tab === 'home' && <Home locale={locale} setLocale={setLocale} openDetail={openDetail}/>} {tab === 'featured' && <Featured locale={locale} setLocale={setLocale} openDetail={openDetail}/>} {tab === 'saved' && <Home saved locale={locale} setLocale={setLocale} openDetail={openDetail}/>} {tab === 'settings' && <Settings locale={locale} setLocale={setLocale}/>}</div>{showingDetail && (article ? <Detail article={article} locale={locale} back={back}/> : <p className="state">{t.loading}</p>)}</div>{!showingDetail && <nav>{([['home', '⌂', t.home], ['featured', '✦', t.featuredNews], ['saved', '☆', t.saved], ['settings', '⚙', t.settings]] as [Tab, string, string][]).map(([id, icon, label]) => <button className={tab === id ? 'nav-active' : ''} onClick={() => setTab(id)} key={id}><span>{icon}</span>{label}</button>)}</nav>}</main> }
